Updated README
SRA-VJTI/RISC-V-CPU pull request #1
Opened 2024-01-14 13:36 UTC by saishock1504

Changes made in README:-

- Removed whiteboard diagram of CPU
- Added installation paths for used softwares
- Updated and added new command for simulation and for flashing on FPGA

2024-01-14 13:47 UTC, SuperChamp234 requested changes

2024-01-14 13:47 UTC, SuperChamp234 commented on README.md
>  #### The RISC-V CPU will be implemented with IMAF instruction extensions, and also verified using custom verification methods.
Let’s not talk about future objectives, and try to describe the CPU in its current. State. The first thing in a README should be describing what we have in the repository.

2024-01-14 13:47 UTC, SuperChamp234 commented on README.md
>  Due to being open-source in nature, RISC-V provides a vital step in designing, building and testing new hardware without paying any license fees or royalties
This seems unnecessary.

2024-01-14 13:47 UTC, SuperChamp234 commented on README.md
> +First we need to write a C code for the operation we need to perform on our CPU(For example:- We have written a script that generates fibonacci series),
Why are you writing this para as “We”. Reword this paragraph simply as instructions.

“An example C program can be loaded on the CPU’s program memory for operations.”
“We provide an example code under `sim/fibonacci.c` for testing purposes."

2024-01-14 13:47 UTC, SuperChamp234 commented on README.md
> +All the necessary commands have been added to the Makefile
Specify path of the makefile

2024-01-14 13:47 UTC, SuperChamp234 commented on README.md
>  - Quartus Prime IDE
Remove this as we no longer use it.

2024-01-14 13:47 UTC, SuperChamp234 commented on README.md
> +- [x] Verify CPU output with every cases, possible, edge and false cases.
Verification is not done. Ideally, there should be a script that will formally verify the CPU and display results.

2024-01-14 13:47 UTC, SuperChamp234 commented on README.md
Please add instructions or a list of software which are needed to run the CPU. Provide links with instructions to install/build.

2024-01-14 13:51 UTC, NachtSpyder04 commented on README.md
I have added softwares in the Tech stack, should I bring it on top of the document

Also links for installations are also given above in the form of hyperlinks

2024-01-14 13:54 UTC, NachtSpyder04 commented on README.md
> +- [x] Verify CPU output with every cases, possible, edge and false cases.
Ok, will do the changes.

2024-01-14 13:54 UTC, NachtSpyder04 commented on README.md
>  - Quartus Prime IDE
Ok, will do the changes

2024-01-14 13:55 UTC, NachtSpyder04 commented on README.md
> +All the necessary commands have been added to the Makefile
Ok, will do the changes

2024-01-14 13:58 UTC, NachtSpyder04 commented on README.md
>  Due to being open-source in nature, RISC-V provides a vital step in designing, building and testing new hardware without paying any license fees or royalties
Ok, will remove that section.

2024-01-14 13:59 UTC, NachtSpyder04 commented on README.md
>  #### The RISC-V CPU will be implemented with IMAF instruction extensions, and also verified using custom verification methods.
Ok, will do the changes

2024-01-14 13:59 UTC, NachtSpyder04 commented on README.md
> +First we need to write a C code for the operation we need to perform on our CPU(For example:- We have written a script that generates fibonacci series),
Ok, will do the changes

2024-01-14 14:31 UTC, NachtSpyder04 commented
Pushed the suggested changes
Please review it to see if it is appropriate or not

2024-08-05 14:47 UTC, SuperChamp234 commented
Looks good to me!

2024-08-05 14:48 UTC, SuperChamp234 approved these changes
looks good to me!

2024-08-05 14:48 UTC, merged